# AppVeyor configuration file
# Call on gradle to build and run tests
build_script:
  - gradlew.bat assemble checkstyleMain checkstyleTest

test_script:
  - gradlew.bat test

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11  # Use 64-bit Java
